### ISSUE TITLE
Map<String, TagLibraryInfo> tags = new HashMap<>(); Does NOT works.

### ISSUE THREAD

**Issue by gencube** [undertow-io/jastow#22]
Such code added to support JSTL
```
public static Map<String, TagLibraryInfo> toJSTL() {
        Map<String, TagLibraryInfo> tags = new HashMap<>();

        String[][] jstlInfos = {
            {"http://java.sun.com/jstl/core_rt", "c-1_0-rt.tld", "1.0", "1.0"},
            {"http://java.sun.com/jstl/core", "c.tld", "1.0", "1.1"},
            {"http://java.sun.com/jsp/jstl/functions", "fn.tld", "1.0", "1.1"},
            {"http://java.sun.com/jstl/fmt_rt", "fmt-1_0-rt.tld", "1.0", "1.0"},
            {"http://java.sun.com/jstl/fmt", "fmt.tld", "1.0", "1.1"},            
            {"http://java.sun.com/jsp/jstl/sql", "sql.tld", "1.0", "1.1"},
            {"http://java.sun.com/jstl/sql_rt", "sql-1_0-rt.tld", "1.0", "1.1"},            
            {"http://java.sun.com/jsp/jstl/xml", "x.tld", "1.0", "1.1"},
            {"http://java.sun.com/jstl/xml_rt", "x-1_0-rt.tld", "1.0", "1.1"}
        };

        for (String[] jstlinfo : jstlInfos) {
            TagLibraryInfo info = new TagLibraryInfo();
            info.setUri(jstlinfo[0]);
            // ### OR this ("/"+jstlinfo[1]); ERROR STILL EXIST.
            info.setPath("/META-INF/"+jstlinfo[1]);
            info.setVersion(jstlinfo[2]);
            info.setTlibversion(jstlinfo[3]);
            // ### OR this ("/META-INF/"+jstlinfo[1]);  ERROR STILL EXIST.
            tags.put("/"+jstlinfo[1], info);
        }

        return tags;
    }
```
Full Sample here.
https://github.com/gencube/JstlJastow

It does not seems to work.

**Comment by gencube** [comment]
Issue resolved.

**Comment by spinneret** [comment]
@gencube How was this resolved? Is the code available on github? Should the code be incorporated into Jastow as a utility to enable easier integration of JSTL?

**Comment by gencube** [comment]
Should the code be incorporated into Jastow as a utility to enable easier integration of JSTL? <<< I am NOT the developer of Jastow. Only user, hence cannot determine its incorporation.

**Comment by spinneret** [comment]
Do you still have the code you used to incorporate JSTL? Is it public and on github?

**Comment by gencube** [comment]
Actually, after digging around for 8 hours I used these code fragment:
https://github.com/wildfly/wildfly/blob/master/undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java#L1202-L1321

AND

import org.jboss.metadata.parser.jsp.TldMetaDataParser;

https://github.com/sgotti/jboss-as/blob/master/web-common/src/main/java/org/jboss/as/web/common/SharedTldsMetaDataBuilder.java#L95-L111

AND 

imported and used this library from:
org.jboss.metadata.parser.jsp.TldMetaDataParser

public static TldMetaData parse(XMLStreamReader reader) throws XMLStreamException {
}

From this URL.
http://grepcode.com/file/repository.jboss.org/nexus/content/repositories/releases/org.jboss.metadata/jboss-metadata-web/7.2.2.Final/org/jboss/metadata/parser/jsp/TldMetaDataParser.java#TldMetaDataParser.parse%28javax.xml.stream.XMLStreamReader%29

Hope this helps.

**Comment by spinneret** [comment]
Wow! Thanks!

**Comment by gencube** [comment]
Github, Grepcode, Massapi Real place for many many code sample solution.
What is yours list of sites?

**Comment by spinneret** [comment]
I wish the JSTL integration was more straightforward. I would easiky use Undertow as my main framework. It is so awesome for everything else.
