### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by vimalprakashts** [undertow-io/jastow#29]
Hi team,

how to use this ? I not finding any detailed documentation for this.

**Comment by ctomc** [comment]
It is meant to be used as part of undertow web server.

you can see usage as part of tests https://github.com/undertow-io/jastow/blob/master/src/test/java/io/undertow/test/jsp/basic/SimpleJspTestCase.java

**Comment by vimalprakashts** [comment]
@ctomc  thankyou
