### ISSUE TITLE
Should Jsp Specification Version be 3.1 instead of 2.3

### ISSUE THREAD

**Issue by dungtripham** [undertow-io/jastow#82]
JSP Version: <%= JspFactory.getDefaultFactory().getEngineInfo().getSpecificationVersion() %> <br>
returns:
JSP Version: 2.3

**Comment by dungtripham** [comment]
I see its version in pom file  <version.jakarta.servlet.jsp.jakarta-servlet-jsp-api>3.1.0</version.jakarta.servlet.jsp.jakarta-servlet-jsp-api>

**Comment by ropalka** [comment]
You're right @dungtripham . Thanks for reporting this problem. Here's the follow up issue:
https://issues.redhat.com/browse/UNDERTOW-2317
